# Data Cleaning

Step of Data Cleaning:

    1. Load Dataset
    2. Handle missing values
    3. Handle duplicate values
    4. Clean and transform Datasets
    5. store clean dataset for next workflow steps

# Librairies

In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load Data
Data ist stored as an Excel file. So, we use Pandas to load data

In [ ]:

def load_data(file_path):
    data= pd.read_csv(file_path, sep=";")
    return data

file_path="../Data/useCarData.csv"

data= load_data(file_path)
print(data.head())

  Brand and model  Year of manufacture  Mileage  Engine power (hp) Fuel type  \
0    BMW 3 Series                 2013   114835                141    petrol
1     Skoda Fabia                 2012   166151                135    diesel
2          BMW X3                 2016   168960                196    petrol
3    BMW 5 Series                 2008   117128                122    petrol
4   Skoda Octavia                 2015   102098                 60    petrol

  Transmission type Trim level / Equipment line Vehicle condition    Origin  \
0            manual                     Limited        acceptable    dealer
1            manual                        Base        acceptable   private
2         automatic                       Sport              good  trade-in
3            manual                     Comfort         very good    import
4         automatic                     Comfort              good    dealer

   Energy consumption  ...  Panel gaps & fit     Windows & lights  \
0                 7.5  ...            Uneven                Clear
1                 8.0  ...   Slightly uneven  Cracked or yellowed
2                 4.9  ...            Uneven      Minor scratches
3                 5.5  ...              Even      Minor scratches
4                 5.6  ...              Even      Minor scratches

   Tires & wheels  Undercarriage & edges Seats & upholstery  \
0         Damaged                  Clean               Torn
1     Uneven wear             Oil stains               Torn
2       Even wear             Minor rust               Worn
3         Damaged           Water damage               Worn
4         Damaged             Oil stains          Excellent

  Dashboard & controls Headliner & carpets         Trunk      Odor  \
0                 Worn             Sagging          Rust     Smoke
1                 Good             Sagging         Clean  Moisture
2                 Worn        Minor stains  Minor stains  Pet odor
3            Excellent               Clean          Rust     Smoke
4                 Good               Clean          Rust  Moisture

                                              Extras
0  Alloy wheels, Panoramic roof, Lane-keeping ass...
1                                     Panoramic roof
2  Panoramic roof, Alloy wheels, Lane-keeping ass...
3                  Alloy wheels, Lane-keeping assist
4  Lane-keeping assist, Trailer hitch, Alloy whee...

[5 rows x 41 columns]

In [26]:
print(data.columns)

Index(['Brand and model', 'Year of manufacture', 'Mileage',
       'Engine power (hp)', 'Fuel type', 'Transmission type',
       'Trim level / Equipment line', 'Vehicle condition', 'Origin',
       'Energy consumption', 'Power output (kW)', 'Category / Vehicle type',
       'Engine displacement (cc)', 'Price (EUR)', 'Color',
       'Air conditioning / Climate control', 'Transmission', 'Number of doors',
       'Number of seats', 'Drive type', 'Interior equipment / Interior design',
       'Accident history', 'Number of previous owners',
       'Maintenance / service history', 'Inspection status (TÜV/HU)',
       'Sale price', 'Region / city', 'Listing duration', 'Seller type',
       'Dealer rating', 'Body & paint', 'Panel gaps & fit', 'Windows & lights',
       'Tires & wheels', 'Undercarriage & edges', 'Seats & upholstery',
       'Dashboard & controls', 'Headliner & carpets', 'Trunk', 'Odor',
       'Extras'],
      dtype='object')

First of all, we split test data for later analysis

In [47]:
#x=data.drop(['Price (EUR)','Sale price'], axis=1)
x= data.drop(['Price (EUR)'], axis=1)  # predict Variable

y=data['Price (EUR)']

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
data= x_train.copy()
data['Price (EUR)']= y_train
#print(data.isnull().sum())

# Fill missing values with a value
 In the dataset we have 15 missing row Odor, 14 row Daeler rating and 6 with Extras row

In [33]:
data['Odor'] = data['Odor'].fillna("Unknown")
data['Extras'] = data['Extras'].fillna("None")
data['Dealer rating'] = data['Dealer rating'].fillna(data['Dealer rating'].median())

print(data.isnull().sum())

Brand and model                         0
Year of manufacture                     0
Mileage                                 0
Engine power (hp)                       0
Fuel type                               0
Transmission type                       0
Trim level / Equipment line             0
Vehicle condition                       0
Origin                                  0
Energy consumption                      0
Power output (kW)                       0
Category / Vehicle type                 0
Engine displacement (cc)                0
Color                                   0
Air conditioning / Climate control      0
Transmission                            0
Number of doors                         0
Number of seats                         0
Drive type                              0
Interior equipment / Interior design    0
Accident history                        0
Number of previous owners               0
Maintenance / service history           0
Inspection status (TÜV/HU)              0
Region / city                           0
Listing duration                        0
Seller type                             0
Dealer rating                           0
Body & paint                            0
Panel gaps & fit                        0
Windows & lights                        0
Tires & wheels                          0
Undercarriage & edges                   0
Seats & upholstery                      0
Dashboard & controls                    0
Headliner & carpets                     0
Trunk                                   0
Odor                                    0
Extras                                  0
Price (EUR)                             0
dtype: int64

## Columns Typecasting 
Check the columns type. Here we should make sure that the data type of each column

In [32]:
print(data.dtypes)

Brand and model                          object
Year of manufacture                       int64
Mileage                                   int64
Engine power (hp)                         int64
Fuel type                                object
Transmission type                        object
Trim level / Equipment line              object
Vehicle condition                        object
Origin                                   object
Energy consumption                      float64
Power output (kW)                       float64
Category / Vehicle type                  object
Engine displacement (cc)                  int64
Color                                    object
Air conditioning / Climate control       object
Transmission                             object
Number of doors                           int64
Number of seats                           int64
Drive type                               object
Interior equipment / Interior design     object
Accident history                         object
Number of previous owners                 int64
Maintenance / service history            object
Inspection status (TÜV/HU)               object
Region / city                            object
Listing duration                         object
Seller type                              object
Dealer rating                           float64
Body & paint                             object
Panel gaps & fit                         object
Windows & lights                         object
Tires & wheels                           object
Undercarriage & edges                    object
Seats & upholstery                       object
Dashboard & controls                     object
Headliner & carpets                      object
Trunk                                    object
Odor                                     object
Extras                                   object
Price (EUR)                               int64
dtype: object

In [49]:
#data.info

## Handle Duplicate Rows

In [53]:
duplicate_rows=data.duplicated()

if duplicate_rows.any():
    print(" There ist Duplicate rows")
    print(f"Number of duplicate rows: {duplicate_rows.sum()}")
    data= data.drop_duplicates()
else:
    print("No duplicate rows")
print(f"Shape of data after removing duplicates: {data.shape}")

No duplicate rows
Shape of data after removing duplicates: (40, 40)

## Numerical Sanity check

In [61]:
numerical_cols= data.select_dtypes(include=['int64','float64' ]).columns.tolist()
print(data[numerical_cols].columns)
data[numerical_cols].describe()

Index(['Year of manufacture', 'Mileage', 'Engine power (hp)',
       'Energy consumption', 'Power output (kW)', 'Engine displacement (cc)',
       'Number of doors', 'Number of seats', 'Number of previous owners',
       'Dealer rating', 'Price (EUR)'],
      dtype='object')

,Year of manufacture,Mileage,Engine power (hp),Energy consumption,Power output (kW),Engine displacement (cc),Number of doors,Number of seats,Number of previous owners,Dealer rating,Price (EUR)
count,40.00000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000
mean,2015.50000,90912.950000,123.600000,6.817500,92.162500,1712.250000,4.225000,4.825000,3.050000,3.91500,24246.900000
std,5.34454,42442.417068,41.566629,2.187715,30.997946,393.472949,0.576795,0.675107,1.319479,0.43885,12622.902762
min,2006.00000,7604.000000,60.000000,3.100000,44.700000,1000.000000,3.000000,2.000000,1.000000,2.60000,1500.000000
25%,2011.00000,60586.750000,94.500000,5.175000,70.450000,1400.000000,4.000000,5.000000,2.000000,3.90000,14522.750000
50%,2016.50000,101158.000000,120.500000,6.500000,89.850000,1600.000000,4.000000,5.000000,3.000000,3.90000,24884.000000
75%,2019.25000,114463.250000,155.250000,8.175000,115.775000,2000.000000,5.000000,5.000000,4.000000,4.02500,32952.250000
max,2024.00000,183288.000000,198.000000,15.100000,147.600000,2500.000000,5.000000,5.000000,5.000000,4.90000,51862.000000

## Categorical Sanity Check
I declare all categorical variables
    . Brand and model
    . Fuel type
    . Transmission type
    . Trim level / Equipment line
    . Vehicle condition
    . Origin,
    . Category / Vehicle type
    . Color
    . Air conditioning / Climate control 
    . Transmission
     'Drive type',
       'Interior equipment / Interior design', 'Accident history',
       'Maintenance / service history', 'Inspection status (TÜV/HU)',
       'Region / city', 'Listing duration', 'Seller type', 'Body & paint',
       'Panel gaps & fit', 'Windows & lights', 'Tires & wheels',
       'Undercarriage & edges', 'Seats & upholstery', 'Dashboard & controls',
       'Headliner & carpets', 'Trunk', 'Odor', 'Extras',
      dtype='object'

In [62]:
categorical_cols= data.select_dtypes(include=['object' ]).columns.tolist()
print(data[categorical_cols].columns)
data[categorical_cols].describe()

Index(['Brand and model', 'Fuel type', 'Transmission type',
       'Trim level / Equipment line', 'Vehicle condition', 'Origin',
       'Category / Vehicle type', 'Color',
       'Air conditioning / Climate control', 'Transmission', 'Drive type',
       'Interior equipment / Interior design', 'Accident history',
       'Maintenance / service history', 'Inspection status (TÜV/HU)',
       'Region / city', 'Listing duration', 'Seller type', 'Body & paint',
       'Panel gaps & fit', 'Windows & lights', 'Tires & wheels',
       'Undercarriage & edges', 'Seats & upholstery', 'Dashboard & controls',
       'Headliner & carpets', 'Trunk', 'Odor', 'Extras'],
      dtype='object')

,Brand and model,Fuel type,Transmission type,Trim level / Equipment line,Vehicle condition,Origin,Category / Vehicle type,Color,Air conditioning / Climate control,Transmission,...,Panel gaps & fit,Windows & lights,Tires & wheels,Undercarriage & edges,Seats & upholstery,Dashboard & controls,Headliner & carpets,Trunk,Odor,Extras
count,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
unique,23,4,2,7,6,4,7,9,4,2,...,3,3,4,4,4,4,4,4,4,37
top,Skoda Kodiaq,petrol,automatic,Excellence,good,trade-in,Van,grey,no AC,automatic,...,Uneven,Cracked or yellowed,New,Clean,Torn,Excellent,Minor stains,Minor stains,Smoke,"Panoramic roof, Lane-keeping assist, Alloy wheels"
freq,3,19,25,8,17,13,9,9,13,25,...,18,15,12,12,16,11,12,12,13,2

In [65]:
def cat_checker(catIndex):
    value= np.sort(data[categorical_cols[catIndex]].unique())
    return categorical_cols[catIndex], value

cat_checker(0)

('Brand and model',
 array(['Audi A3', 'Audi A4', 'BMW 3 Series', 'BMW X5', 'Ford Focus',
        'Ford Mondeo', 'Hyundai Tucson', 'Hyundai i10', 'Hyundai i30',
        'Mercedes-Benz C-Class', 'Opel Astra', 'Opel Insignia',
        'Renault Captur', 'Renault Clio', 'Renault Mégane', 'Skoda Fabia',
        'Skoda Kodiaq', 'Skoda Octavia', 'Toyota Corolla', 'Toyota Yaris',
        'Volkswagen Golf', 'Volkswagen Polo', 'Volkswagen Tiguan'],
       dtype=object))

## CHECKPOINT

In [ ]:
%store x_test
%store y_test
%store data
%store numerical_cols
%store categorical_cols